export default [
  {name:'其他', icon:'others'},
  {name: '三餐', icon: 'meals'},
  {name:'酒水',icon: 'beer'},
  {name:'孩子',icon:'child'},
  {name:'衣服',icon:'clothes'},
  {name:'化妆品',icon:'cosmetic'},
  {name:'数码产品',icon:'digital-product'},
  {name:'娱乐',icon:'entertainment'},
  {name:'住房',icon:'house'},
  {name:'保险',icon:'insurance'},
  {name:'红包',icon:'luck-money'},
  {name:'医疗',icon:'medicine'},
  {name:'商户',icon:'merchant'},
  {name:'必需品',icon:'necessities'},
  {name:'停车费', icon: 'parking-fee'},
  {name:'宠物',icon:'pet'},
  {name:'手机',icon:'phone'},
  {name:'公共服务',icon:'public-service'},
  {name:'手机费',icon:'recharge'},
  {name:'工资',icon:'salary'},
  {name:'零食',icon:'snacks'},
  {name:'运动',icon:'sports'},
  {name:'股票',icon:'stock'},
  {name:'学习',icon:'study'},
  {name:'交通',icon:'traffic'},
  {name:'转账',icon:'transfer'},
  {name:'旅游',icon:'travel'},
  {name:'水电费',icon:'utility-bill'},
]